games = " Games = Alien Invasion"
import time
print("Hello")
time.sleep(1)
print("I am JoshBot Version 3.2.2")
time.sleep(1)
password = input("Please Enter JoshBot Password")
if password == "42":
    time.sleep(1)
    print("Laoding JoshBot 1.0")
    time.sleep(1)
    print("...")
    time.sleep(1)
    print("...")
    time.sleep(1)
    print("...")
    time.sleep(1)
while not password == "42":
    time.sleep(1)
    password = input("!!ERROR!! !!JOSHBOT PASSWORD INCORECT!! !!ENTER CORRECT PASSWOR!!")
    if password == "42":
        print("Laoding JoshBot 1.0")
        time.sleep(1)
        print("...")
        time.sleep(1)
        print("...")
        time.sleep(1)
        print("...")
        time.sleep(1)
        print("LOADED")
        time.sleep(1)
print("      ")
print("      ")
choice = input("What Do You Want To See?")
if choice == "games":
    time.sleep(1)
    print(games)
choicegame = input("What Game Do You Want To Play?")
if choicegame == "Alien Invasion":
    time.sleep(1)
    print("LOADING ALIEN INVASION")
    time.sleep(1)
    print("...")
    time.sleep(1)
    print("...")
    time.sleep(1)
    print("...")
    time.sleep(1)
    print("LOADED")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    time.sleep(1)
    print("Welcome To Alien Invasion!!!")
    print("Please Don't Use Capitals!!!")
    time.sleep(3)
    print("Oh No! Aliens are invading!!")
    time.sleep(1)
    choiceroomfirst = input("Do you want to run outside?!")
    if choiceroomfirst == "yes":
        print("You run outside")
        time.sleep(1)
        print("OMG! There is a random alien space laser on the floor!")
        gunchoicefirst = input("Do you want to pick it up?")
        if gunchoicefirst == "yes":
            print("You picked up the plasma gun")
            time.sleep(1)
            print("It blew up and killed you :(")
            time.sleep(1)
            print("GAME OVER")
            time.sleep(2)
        if not gunchoicefirst == "yes":
            print("You leave the gun where it is")
            time.sleep(1)
            print("The gun promptly blew up, that was a close one!")
            time.sleep(1)
            print("OMG! an alien spaceship just abducted you!")
            spaceshipchoicefirst = input("Do you want to jump out of the tractor beam?")
            if spaceshipchoicefirst == "yes":
                time.sleep(1)
                print("You jumped out of the tractor beam")
                time.sleep(1)
                print("SPLAT!")
                time.sleep(1)
                print("GAME OVER")
                time.sleep(2)
            if not spaceshipchoicefirst == "yes":
                print("you stayed where you were and the ship pulled you into it!")
                time.sleep(1)
                alienbattlechoicefirst = input("there is an alien waiting for with a cup and what seems to be a laser cannon, do you want to punch him in the face?")
                if alenbatttlechoicefirst == "yes":
                    time.sleep(1)
                    print("You punched him in the face")
                    time.sleep(1)
                    print("He promptly exploded into pink goop")
                    time.sleep(1)
                    print("Another alien came in and killed you :()")
                    time.sleep(1)
                    print("GAME OVER")
                    time.sleep(13)
                if not alienbattlechoicefirst == "yes":
                    time.sleep(1)
                    print("You did nothing")
                    time.sleep(1)
                    print("The alien foured some tea out of the gun and gave it to you")
                    time.sleep(1)
                    teachoice = input("Do you want to drink the tea?")
                    if teachoice == "yes":
                        time.sleep(1)
                        print("You drank the tea")
                        time.sleep(1)
                        print("it tasted rather nice")
                        time.sleep(1)
                        print("Suddently the alien ship exploded into rainbows and you landed in unicorn land!")
                        time.sleep(10)
                    if teachoice == "no":
                        time.sleep(1)
                        print("you did not drink the tea and then a random unicorn ate you head and you died :()")
                        time.sleep(1)
                        print("GAMEOVER")
                        time.sleep(1)
    if not choiceroomfirst == "yes":
       print("You stayed where you are")
       time.sleep(1)
       print("Oh No! The aliens burst into the house! They ate your face :()")
       time.sleep(2)
       print("GAME OVER")
       time.sleep(2)
while not choicegame == ("Alien Invasion"):
    print("!!ERROR!! !!INVALID GAME!!")
    time.sleep(1)
    choicegame = input("What Game Do You Want To Play?")
    if choicegame == "Alien Invasion":
    time.sleep(1)
    print("LOADING ALIEN INVASION")
    time.sleep(1)
    print("...")
    time.sleep(1)
    print("...")
    time.sleep(1)
    print("...")
    time.sleep(1)
    print("LOADED")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    time.sleep(1)
    print("Welcome To Alien Invasion!!!")
    print("Please Don't Use Capitals!!!")
    time.sleep(3)
    print("Oh No! Aliens are invading!!")
    time.sleep(1)
    choiceroomfirst = input("Do you want to run outside?!")
    if choiceroomfirst == "yes":
        print("You run outside")
        time.sleep(1)
        print("OMG! There is a random alien space laser on the floor!")
        gunchoicefirst = input("Do you want to pick it up?")
        if gunchoicefirst == "yes":
            print("You picked up the plasma gun")
            time.sleep(1)
            print("It blew up and killed you :(")
            time.sleep(1)
            print("GAME OVER")
            time.sleep(2)
        if not gunchoicefirst == "yes":
            print("You leave the gun where it is")
            time.sleep(1)
            print("The gun promptly blew up, that was a close one!")
            time.sleep(1)
            print("OMG! an alien spaceship just abducted you!")
            spaceshipchoicefirst = input("Do you want to jump out of the tractor beam?")
            if spaceshipchoicefirst == "yes":
                time.sleep(1)
                print("You jumped out of the tractor beam")
                time.sleep(1)
                print("SPLAT!")
                time.sleep(1)
                print("GAME OVER")
                time.sleep(2)
            if not spaceshipchoicefirst == "yes":
                print("you stayed where you were and the ship pulled you into it!")
                time.sleep(1)
                alienbattlechoicefirst = input("there is an alien waiting for with a cup and what seems to be a laser cannon, do you want to punch him in the face?")
                if alenbatttlechoicefirst == "yes":
                    time.sleep(1)
                    print("You punched him in the face")
                    time.sleep(1)
                    print("He promptly exploded into pink goop")
                    time.sleep(1)
                    print("Another alien came in and killed you :()")
                    time.sleep(1)
                    print("GAME OVER")
                    time.sleep(13)
                if not alienbattlechoicefirst == "yes":
                    time.sleep(1)
                    print("You did nothing")
                    time.sleep(1)
                    print("The alien foured some tea out of the gun and gave it to you")
                    time.sleep(1)
                    teachoice = input("Do you want to drink the tea?")
                    if teachoice == "yes":
                        time.sleep(1)
                        print("You drank the tea")
                        time.sleep(1)
                        print("it tasted rather nice")
                        time.sleep(1)
                        print("Suddently the alien ship exploded into rainbows and you landed in unicorn land!")
                        time.sleep(10)
                    if teachoice == "no":
                        time.sleep(1)
                        print("you did not drink the tea and then a random unicorn ate you head and you died :()")
                        time.sleep(1)
                        print("GAMEOVER")
                        time.sleep(1)
    if not choiceroomfirst == "yes":
       print("You stayed where you are")
       time.sleep(1)
       print("Oh No! The aliens burst into the house! They ate your face :()")
       time.sleep(2)
       print("GAME OVER")
       time.sleep(2)
