games = " Games = Toilet Adventure"
import time
print("Hello")
time.sleep(1)
print("I am JoshBot")
time.sleep(1)
password = input("Please Enter JoshBot Password")
if password == "42":
    print("Laoding JoshBot 1.0")
    time.sleep(1)
    print("...")
    time.sleep(1)
    print("...")
    time.sleep(1)
    print("...")
    time.sleep(1)
while not password == "42":
    password = input("!!ERROR!! !!JOSHBOT PASSWORD INCORECT!! !!ENTER CORRECT PASSWOR!!")
    if password == "42":
        print("Laoding JoshBot 1.0")
        time.sleep(1)
        print("...")
        time.sleep(1)
        print("...")
        time.sleep(1)
        print("...")
        time.sleep(1)
        print("LOADED")
        time.sleep(1)
print("      ")
print("      ")
choice = input("What Do You Want To See?")
if choice == "games":
    print(games)
choicegame = input("What Game Do You Want To Play?")
if choicegame == "Toilet Adventure":
    print("LOADING TOILET ADVENTURE")
    time.sleep(1)
    print("...")
    time.sleep(1)
    print("...")
    time.sleep(1)
    print("...")
    print("!!ERROR!! !!GAME FILES NOT LOADED!!")
    time.sleep(1)
    choiceerror = input("Would You Like To Show Full Error Report?")
    if choiceerror == "yes":
          print("LOADING TOILET ADVENTURE;FINDING FILES;!!ERROR!! !!FILES NOT FOUND!!")
          time.sleep(10)
